const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = {
  screen: 'intro', plannerIndex: 0, quizIndex: 0,
  answers: JSON.parse(localStorage.getItem('spiderDateAnswers') || '{}'),
  quiz: []
};
const planner = [
  {key:'saludo', title:'¿Cómo quieres que te salude cuando te vea?', hint:'El protocolo de bienvenida es importante.', type:'single', options:[['💋','Beso apasionado'],['🍑','Cachetada en el culo'],['🦐','Salto de gamba'],['🐨','Abrazo de koala'],['🕺','Entrada cinematográfica'],['🎲','Sorpresa tuya']]},
  {key:'comida', title:'¿Dónde comemos antes de la peli?', hint:'Elige sin presión. Mentira: sushi suma puntos.', type:'singleCustom', options:[['🍣','Kaisen'],['🍱','Sushi O'],['🥩','Barbacoa coreana'],['🍻','Tapeo'],['🍝','Italiano'],['🌮','Mexicano']]},
  {key:'peli', title:'¿Qué película vemos?', hint:'Pregunta trampa, pero queda bonito preguntarlo.', type:'single', options:[['🕷️','Spider-Man: Brand New Day'],['🕸️','Spider-Man: Brand New Day pero con palomitas grandes'],['🎬','Spider-Man: Brand New Day y luego debatimos la escena postcréditos']]},
  {key:'outfit', title:'Outfit oficial de la cita', hint:'Elige el mood. Se respetará con solemnidad.', type:'single', options:[['✨','Elegante'],['👕','Casual guapa'],['🕷️','Cosplay de Spider-Man'],['🕸️','Cosplay de Spider-Gwen'],['🧸','Oversize adorable'],['🔥','Sorpresa peligrosa']]},
  {key:'flores', title:'¿Qué flores quieres en tu ramo?', hint:'Puedes elegir varias y añadir las que falten.', type:'multiCustom', options:[['🌹','Rosas'],['🌷','Tulipanes'],['🌻','Girasoles'],['🌸','Peonías'],['🤍','Lirios'],['🪻','Lavanda'],['🌼','Margaritas'],['🌺','Hortensias']]},
  {key:'postre', title:'Postre después de comer', hint:'También vale robarme el mío.', type:'singleCustom', options:[['🍨','Helado'],['🍰','Tarta'],['🧇','Gofre'],['🍫','Chocolate'],['🍓','Algo con fresas'],['🥄','Compartimos postre']]},
  {key:'bebida', title:'Bebida del plan', hint:'Para comer, para después o para fingir que somos adultos funcionales.', type:'singleCustom', options:[['🍹','Cóctel'],['🍷','Vino'],['🥤','Refresco'],['🧋','Bubble tea'],['☕','Café'],['💧','Agua porque somos responsables']]},
  {key:'extras', title:'Extras desbloqueables', hint:'Puedes seleccionar todos los que quieras.', type:'multi', options:[['🚶‍♀️','Paseo'],['📸','Fotos juntos'],['🎮','Arcade'],['🌃','Mirador'],['🎁','Detallito sorpresa'],['🤝','Ir cogidos de la mano'],['🎤','Karaoke'],['🍿','Palomitas gigantes']]},
  {key:'mensaje', title:'Mensaje secreto antes de la cita', hint:'Última oportunidad para añadir condiciones, amenazas o indirectas.', type:'text'}
];
const bank = [
  {d:'Fácil', q:'¿Qué representa el activo en el balance?', a:['Bienes, derechos y otros recursos controlados por la empresa','Sólo las deudas con bancos','Sólo el dinero en caja','Las aportaciones de los socios'], c:0},
  {d:'Fácil', q:'La ecuación básica del patrimonio es:', a:['Activo = Pasivo + Patrimonio neto','Pasivo = Activo + Patrimonio neto','Ingresos = Gastos + Activo','Activo = Gastos - Ingresos'], c:0},
  {d:'Fácil', q:'Una amortización contable recoge principalmente:', a:['La pérdida sistemática de valor de un inmovilizado por uso o tiempo','El pago de una deuda','La compra de existencias','Un ingreso financiero'], c:0},
  {d:'Fácil', q:'La cuenta 572 Bancos c/c pertenece normalmente a:', a:['Activo corriente','Patrimonio neto','Pasivo no corriente','Gastos financieros'], c:0},
  {d:'Media', q:'Si una empresa compra acciones de otra sin intención especulativa a corto plazo, normalmente se clasificarían como:', a:['Activo financiero no destinado a negociar','Existencias','Pasivo financiero','Tesorería'], c:0},
  {d:'Media', q:'El principio de devengo implica que:', a:['Los ingresos y gastos se registran cuando ocurren, no necesariamente cuando se cobran o pagan','Todo se registra al cobrar','Sólo se registran gastos pagados','Los ingresos se registran al final del ejercicio siempre'], c:0},
  {d:'Media', q:'Una diferencia temporaria imponible suele originar:', a:['Un pasivo por impuesto diferido','Un activo por impuesto diferido','Una reserva voluntaria','Una pérdida irreversible'], c:0},
  {d:'Media', q:'El deterioro de valor de un activo se reconoce cuando:', a:['Su valor contable supera su importe recuperable','Su precio de compra sube','Se amortiza totalmente','La empresa obtiene beneficios'], c:0},
  {d:'Difícil', q:'En el método del coste amortizado, el tipo de interés efectivo sirve para:', a:['Distribuir financieramente ingresos o gastos durante la vida del instrumento','Calcular únicamente el IVA','Valorar existencias por FIFO','Determinar dividendos obligatorios'], c:0},
  {d:'Difícil', q:'En una subvención de capital para financiar inmovilizado, su imputación a resultados normalmente se realiza:', a:['En proporción a la amortización del activo financiado','Toda de golpe al concederse siempre','Sólo cuando se vende el activo','Nunca pasa por resultados'], c:0},
  {d:'Difícil', q:'Si la amortización fiscal es mayor que la contable en el ejercicio, se genera inicialmente:', a:['Una diferencia temporaria que revierte en ejercicios futuros','Un ingreso extraordinario automático','Una pérdida definitiva no reversible','Una deuda comercial'], c:0},
  {d:'Difícil', q:'En un arrendamiento financiero para el arrendatario, si se transfieren sustancialmente riesgos y beneficios, se reconoce generalmente:', a:['Un activo por derecho de uso o inmovilizado y una deuda asociada','Sólo un gasto mensual sin deuda','Una existencia comercial','Un ingreso anticipado'], c:0},
  {d:'Fácil', q:'Las existencias son normalmente:', a:['Activo corriente','Pasivo corriente','Patrimonio neto','Inmovilizado intangible siempre'], c:0},
  {d:'Media', q:'El valor razonable se define como:', a:['Precio que se recibiría por vender un activo o se pagaría por transferir un pasivo en una transacción ordenada','Precio histórico sin ajustes','Valor fiscal obligatorio','Importe nominal de una factura'], c:0},
  {d:'Difícil', q:'Una provisión se reconoce cuando existe:', a:['Obligación presente, salida probable de recursos y estimación fiable','Una posibilidad remota sin estimación','Un beneficio futuro seguro','Una factura ya cobrada'], c:0}
];
function save(){localStorage.setItem('spiderDateAnswers', JSON.stringify(state.answers));}
function show(name){state.screen=name; $$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name)); if(name==='planner') renderPlanner(); if(name==='success') renderSummary();}
function toast(t){const el=$('#toast'); el.textContent=t; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200)}
function renderPlanner(){const step=planner[state.plannerIndex], val=state.answers[step.key]; $('#plannerStep').textContent=state.plannerIndex+1; $('#plannerProgress').style.width=`${((state.plannerIndex+1)/planner.length)*100}%`; let html=`<div class="question-card"><h3>${step.title}</h3><p class="hint">${step.hint||''}</p>`;
 if(['single','singleCustom'].includes(step.type)){html+=`<div class="option-grid">${step.options.map(o=>`<button class="option ${val===o[1]?'selected':''}" data-select="${o[1]}"><span class="emoji">${o[0]}</span>${o[1]}</button>`).join('')}</div>`; if(step.type==='singleCustom') html+=`<div class="add-row"><input class="input" id="customInput" placeholder="Escribir otra opción"/><button class="primary" data-action="addCustom">+</button></div>`;}
 if(['multi','multiCustom'].includes(step.type)){const selected=Array.isArray(val)?val:[]; html+=`<div class="chip-area">${step.options.map(o=>`<button class="chip ${selected.includes(o[1])?'selected':''}" data-toggle="${o[1]}">${o[0]} ${o[1]}</button>`).join('')}</div>`; if(step.type==='multiCustom') html+=`<div class="add-row"><input class="input" id="customInput" placeholder="Añadir flor"/><button class="primary" data-action="addCustomMulti">+</button></div>`;}
 if(step.type==='text') html+=`<textarea class="textarea" id="textAnswer" placeholder="Escribe aquí...">${val||''}</textarea>`;
 html+=`<div class="nav-row"><button class="ghost" data-action="prevPlanner">Atrás</button><button class="primary" data-action="nextPlanner">${state.plannerIndex===planner.length-1?'Bloquear cita':'Siguiente'}</button></div></div>`; $('#plannerContent').innerHTML=html;}
function startQuiz(){state.quiz=[...bank].sort(()=>Math.random()-.5).sort((a,b)=>['Fácil','Media','Difícil'].indexOf(a.d)-['Fácil','Media','Difícil'].indexOf(b.d)).slice(0,12); state.quizIndex=0; renderQuiz(); show('quiz');}
function renderQuiz(){const q=state.quiz[state.quizIndex]; $('#quizStep').textContent=state.quizIndex+1; $('#quizProgress').style.width=`${((state.quizIndex+1)/12)*100}%`; $('#difficultyLabel').textContent=`Nivel ${q.d.toLowerCase()}`; const opts=q.a.map((x,i)=>({x,i})).sort(()=>Math.random()-.5); $('#quizContent').innerHTML=`<h3>${q.q}</h3><div class="answer-list">${opts.map(o=>`<button class="answer" data-answer="${o.i}">${o.x}</button>`).join('')}</div>`;}
function renderSummary(){const map={saludo:'Saludo',comida:'Comida',peli:'Película',outfit:'Outfit',flores:'Flores',postre:'Postre',bebida:'Bebida',extras:'Extras',mensaje:'Mensaje secreto'}; $('#summary').innerHTML=Object.entries(map).map(([k,l])=>{let v=state.answers[k]; if(Array.isArray(v)) v=v.join(', '); if(!v) v='No especificado'; return `<div class="summary-item"><strong>${l}</strong><span>${v}</span></div>`}).join('');}
function copySummary(){const txt='Cita desbloqueada:\n'+Object.entries(state.answers).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v}`).join('\n'); navigator.clipboard?.writeText(txt); toast('Resumen copiado');}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action; const step=planner[state.plannerIndex];
 if(e.target.closest('[data-select]')){state.answers[step.key]=e.target.closest('[data-select]').dataset.select; save(); renderPlanner();}
 if(e.target.closest('[data-toggle]')){const x=e.target.closest('[data-toggle]').dataset.toggle; const arr=Array.isArray(state.answers[step.key])?[...state.answers[step.key]]:[]; arr.includes(x)?arr.splice(arr.indexOf(x),1):arr.push(x); state.answers[step.key]=arr; save(); renderPlanner();}
 if(e.target.closest('[data-answer]')){const btn=e.target.closest('[data-answer]'), ok=Number(btn.dataset.answer)===state.quiz[state.quizIndex].c; btn.classList.add(ok?'correct':'wrong'); setTimeout(()=>{if(!ok) show('fail'); else if(state.quizIndex===11) show('success'); else{state.quizIndex++; renderQuiz();}},550)}
 if(!a)return; if(a==='start'){show('planner')} if(a==='back'){state.plannerIndex=Math.max(0,state.plannerIndex-1); state.plannerIndex===0?show('intro'):renderPlanner()} if(a==='prevPlanner'){state.plannerIndex=Math.max(0,state.plannerIndex-1); renderPlanner()} if(a==='nextPlanner'){if(step.type==='text') state.answers[step.key]=$('#textAnswer').value.trim(); save(); if(state.plannerIndex<planner.length-1){state.plannerIndex++; renderPlanner()}else show('locked')} if(a==='addCustom'){const v=$('#customInput').value.trim(); if(v){state.answers[step.key]=v; save(); renderPlanner()}} if(a==='addCustomMulti'){const v=$('#customInput').value.trim(); if(v){const arr=Array.isArray(state.answers[step.key])?[...state.answers[step.key]]:[]; arr.push(v); state.answers[step.key]=arr; save(); renderPlanner()}} if(a==='startQuiz'||a==='retryQuiz') startQuiz(); if(a==='exitQuiz'||a==='reviewPlan') show('locked'); if(a==='reserve') show('ticket'); if(a==='restart'){state.plannerIndex=0; show('planner')} if(a==='share') copySummary();});
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
show('intro');
